version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading-bot
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - APCA_BASE_URL=${APCA_BASE_URL}
      - DATA_API_URL=${DATA_API_URL}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - POSITION_SIZE_USD=${POSITION_SIZE_USD:-500}
      - POLL_INTERVAL_SECONDS=${POLL_INTERVAL_SECONDS:-60}
      - BASE_STOP_LOSS_PERCENT=${BASE_STOP_LOSS_PERCENT:-8.0}
      - BASE_TAKE_PROFIT_PERCENT=${BASE_TAKE_PROFIT_PERCENT:-2.0}
      - MIN_STOP_LOSS_PERCENT=${MIN_STOP_LOSS_PERCENT:-1.0}
      - MIN_TAKE_PROFIT_PERCENT=${MIN_TAKE_PROFIT_PERCENT:-1.0}
      - SCREENING_POOL_SIZE=${SCREENING_POOL_SIZE:-1000}
      - TOP_CANDIDATES_COUNT=${TOP_CANDIDATES_COUNT:-10}
      - RISK_PER_TRADE_PERCENT=${RISK_PER_TRADE_PERCENT:-1.0}
      - ML_TRAINING_DATA_LIMIT=${ML_TRAINING_DATA_LIMIT:-1000}
      - MIN_VOLUME_FOR_SCREENING=${MIN_VOLUME_FOR_SCREENING:-100000}
    volumes:
      - ./data:/app/data
    restart: unless-stopped